import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header"
import Footer from "@/components/Footer"
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter'
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Conduit",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
        <AppRouterCacheProvider>
        {children}
        </AppRouterCacheProvider>
        <Footer/></body>
    </html>
  );
}
